/**
 * Shared credential loader for CLI scripts.
 *
 * - If .env exists → load it silently
 * - If .env is missing → prompt the user interactively and create it
 *
 * Safe for local dev only. Credentials stay on disk, never sent to any server.
 * .env is already in .gitignore so it won't be committed.
 */

import fs from 'node:fs';
import path from 'node:path';
import { createInterface } from 'node:readline/promises';

const ENV_PATH = path.resolve(process.cwd(), '.env');

// ── Parse a .env file into process.env ───────────────────────────────────────
function parseAndApply(content) {
  for (const line of content.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq === -1) continue;
    const key = t.slice(0, eq).trim();
    if (!process.env[key]) process.env[key] = t.slice(eq + 1).trim();
  }
}

// ── Prompt the user to enter credentials, then write .env ───────────────────
async function promptAndCreate() {
  console.log(`
  ┌─────────────────────────────────────────────────┐
  │   BigCommerce CLI — First Time Setup            │
  └─────────────────────────────────────────────────┘

  No .env file found. Enter your BigCommerce store
  credentials below — they will be saved to .env on
  this machine and never committed to git.

  Where to find them:
    BC Admin → Settings → API → Store-level API Accounts
`);

  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  let storeHash = '';
  let accessToken = '';

  try {
    storeHash   = (await rl.question('  Store Hash    : ')).trim();
    accessToken = (await rl.question('  Access Token  : ')).trim();
  } finally {
    rl.close();
  }

  if (!storeHash || !accessToken) {
    console.error('\n  Error: both Store Hash and Access Token are required.\n');
    process.exit(1);
  }

  const envContent = [
    '# BigCommerce store credentials',
    '# Generated by bc-widget CLI — do not commit this file',
    `BC_STORE_HASH=${storeHash}`,
    `BC_ACCESS_TOKEN=${accessToken}`,
  ].join('\n') + '\n';

  fs.writeFileSync(ENV_PATH, envContent, 'utf8');
  console.log('\n  ✓  Credentials saved to .env\n');

  process.env.BC_STORE_HASH   = storeHash;
  process.env.BC_ACCESS_TOKEN = accessToken;
}

// ── Update a single key in the existing .env file ───────────────────────────
export function updateEnvKey(key, value) {
  if (!fs.existsSync(ENV_PATH)) return;
  let content = fs.readFileSync(ENV_PATH, 'utf8');
  const regex = new RegExp(`^${key}=.*$`, 'm');
  if (regex.test(content)) {
    content = content.replace(regex, `${key}=${value}`);
  } else {
    content += `\n${key}=${value}`;
  }
  fs.writeFileSync(ENV_PATH, content, 'utf8');
}

// ── Main export — call this at the top of any CLI script ────────────────────
export async function loadEnv() {
  if (fs.existsSync(ENV_PATH)) {
    parseAndApply(fs.readFileSync(ENV_PATH, 'utf8'));
  } else {
    await promptAndCreate();
  }

  const missing = ['BC_STORE_HASH', 'BC_ACCESS_TOKEN'].filter(k => !process.env[k]);
  if (missing.length) {
    console.error(`\n  Error: missing in .env: ${missing.join(', ')}`);
    console.error(`  Edit ${ENV_PATH} and add the missing values.\n`);
    process.exit(1);
  }
}
