/**
 * Initialise a new client folder.
 *
 * Usage (run from the project root):
 *   npx bcw init <client-name>
 *
 * Creates:
 *   <client-name>/
 *     .env        ← credentials (prompted interactively)
 *
 * After running, cd into the folder and use all bcw commands normally:
 *   cd <client-name>
 *   npx bcw list
 *   npx bcw download
 */

import fs from 'node:fs';
import path from 'node:path';
import { createInterface } from 'node:readline/promises';

const ROOT = process.cwd();

export async function initClient(clientName) {
  if (!clientName) {
    console.error('\n  Usage: npx bcw init <client-name>\n');
    process.exit(1);
  }

  const slug = clientName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

  const clientDir = path.resolve(ROOT, slug);
  const envPath   = path.join(clientDir, '.env');

  // Create client folder
  fs.mkdirSync(clientDir, { recursive: true });

  // Add client folder to .gitignore if not already listed
  const gitignorePath = path.join(ROOT, '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, 'utf8');
    const entry = `/${slug}`;
    if (!content.split('\n').some(l => l.trim() === entry || l.trim() === slug)) {
      fs.appendFileSync(gitignorePath, `\n${entry}\n`, 'utf8');
    }
  }

  if (fs.existsSync(envPath)) {
    console.log(`
  Client "${slug}" already exists with credentials.

  To start working on this client:
    cd ${slug}
`);
    return;
  }

  // Prompt for credentials
  console.log(`
  ┌─────────────────────────────────────────────────┐
  │   Setting up: ${slug.padEnd(33)}│
  └─────────────────────────────────────────────────┘

  Enter BigCommerce credentials for this store.
  They will be saved to ${slug}/.env (never committed to git).

  Where to find them:
    BC Admin → Settings → API → Store-level API Accounts
`);

  const rl = createInterface({ input: process.stdin, output: process.stdout });

  let storeHash   = '';
  let accessToken = '';

  try {
    storeHash   = (await rl.question('  Store Hash    : ')).trim();
    accessToken = (await rl.question('  Access Token  : ')).trim();
  } finally {
    rl.close();
  }

  if (!storeHash || !accessToken) {
    console.error('\n  Error: both Store Hash and Access Token are required.\n');
    process.exit(1);
  }

  const envContent = [
    '# BigCommerce store credentials',
    `# Client: ${slug}`,
    '# Generated by bcw CLI — do not commit this file',
    `BC_STORE_HASH=${storeHash}`,
    `BC_ACCESS_TOKEN=${accessToken}`,
  ].join('\n') + '\n';

  fs.writeFileSync(envPath, envContent, 'utf8');

  console.log(`
  ✓  Client "${slug}" is ready!

  Folder  : ${slug}/
  Env     : ${slug}/.env
  Git     : /${slug} added to .gitignore

  ──────────────────────────────────────────────────
  cd ${slug}
  ──────────────────────────────────────────────────

  Then use any bcw command as normal:
    npx bcw list
    npx bcw download
    npx bcw create <widget-name>
    npx bcw dev <name>
    npx bcw push <name>
`);
}
